# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 23:59
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
                ('author', models.CharField(default=django.contrib.auth.models.User, max_length=40)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
