# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 19:11
from __future__ import unicode_literals

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0004_auto_20160113_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 1, 13, 19, 11, 24, 523121)),
        ),
    ]
